"""empty message

Revision ID: f6d00a40b301
Revises: 8d77c2ea1b16
Create Date: 2023-09-20 11:16:24.800961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d00a40b301'
down_revision = '8d77c2ea1b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campsitelikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campsite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campsite_id'], ['campsites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campsitelikes')
    # ### end Alembic commands ###