"""empty message

Revision ID: 8d77c2ea1b16
Revises: da919ca28526
Create Date: 2023-08-13 22:14:08.184586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d77c2ea1b16'
down_revision = 'da919ca28526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campsites', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campsites', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###